CREATE TABLE user_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    display_name VARCHAR(80) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    role VARCHAR(16) NOT NULL CHECK (role IN ('ADMIN', 'TEACHER', 'STUDENT')),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(120) NOT NULL,
    description VARCHAR(2000) NOT NULL DEFAULT '',
    teacher_id BIGINT NOT NULL REFERENCES user_accounts(id),
    invite_code VARCHAR(12) NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_courses_teacher ON courses(teacher_id);

CREATE TABLE enrollments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    student_id BIGINT NOT NULL REFERENCES user_accounts(id),
    joined_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_enrollment_course_student UNIQUE (course_id, student_id)
);
CREATE INDEX ix_enrollments_student ON enrollments(student_id);

CREATE TABLE assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    title VARCHAR(120) NOT NULL,
    description VARCHAR(4000) NOT NULL DEFAULT '',
    due_at TIMESTAMP WITH TIME ZONE NOT NULL,
    allow_late BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_assignments_course_due ON assignments(course_id, due_at);

CREATE TABLE submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assignment_id BIGINT NOT NULL REFERENCES assignments(id) ON DELETE CASCADE,
    student_id BIGINT NOT NULL REFERENCES user_accounts(id),
    last_version INTEGER NOT NULL DEFAULT 0 CHECK (last_version >= 0),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_submission_assignment_student UNIQUE (assignment_id, student_id)
);
CREATE INDEX ix_submissions_assignment ON submissions(assignment_id);

CREATE TABLE submission_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id BIGINT NOT NULL REFERENCES submissions(id) ON DELETE CASCADE,
    version_number INTEGER NOT NULL CHECK (version_number > 0),
    original_filename VARCHAR(180) NOT NULL,
    storage_key VARCHAR(50) NOT NULL UNIQUE,
    media_type VARCHAR(100) NOT NULL,
    byte_size BIGINT NOT NULL CHECK (byte_size BETWEEN 1 AND 10485760),
    sha256 VARCHAR(64) NOT NULL,
    submitted_at TIMESTAMP WITH TIME ZONE NOT NULL,
    late BOOLEAN NOT NULL,
    CONSTRAINT uq_submission_version UNIQUE (submission_id, version_number)
);
CREATE INDEX ix_versions_submission ON submission_versions(submission_id, version_number DESC);
